
package bigws.hellows;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloWebService", targetNamespace = "http://hellows.bigws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://hellows.bigws/", className = "bigws.hellows.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://hellows.bigws/", className = "bigws.hellows.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
